### ISSUE TITLE
Socket reconnects

### ISSUE THREAD

**Issue by chriskieser** [absa-subatomic/quantum-mechanic#100]
When spinning up Jenkins, the socket to Atomist dies, usually causing a restart. One time it just hung.

`2018-03-22T15:27:56.689Z [m:7:ebcb9ba5-91e7-4c6d-872d-d92c98eac5b1:Bison:DevOpsEnvironmentRequested:106526] [debug] OpenShift client response: {"command":"oc rollout status dc/jenkins --namespace \"bison-core-devops\" ","output":"Deployment config \"jenkins\" waiting on image update\nDeployment config \"jenkins\" waiting on image update\nWaiting for rollout to finish: 0 out of 1 new replicas have been updated...\nWaiting for rollout to finish: 0 out of 1 new replicas have been updated...\nWaiting for rollout to finish: 0 out of 1 new replicas have been updated...\nWaiting for rollout to finish: 0 out of 1 new replicas have been updated...\nWaiting for rollout to finish: 0 of 1 updated replicas are available...\nWaiting for latest deployment config spec to be observed by the controller loop...\nreplication controller \"jenkins-1\" successfully rolled out\n","status":true}
2018-03-22T15:27:56.691Z [m:7:ebcb9ba5-91e7-4c6d-872d-d92c98eac5b1:Bison:DevOpsEnvironmentRequested:106528] [verbose] Executing oc command: oc annotate route jenkins --overwrite "haproxy.router.openshift.io/timeout=120s" --namespace "bison-core-devops"
2018-03-22T15:27:56.966Z [m:7:ebcb9ba5-91e7-4c6d-872d-d92c98eac5b1:Bison:DevOpsEnvironmentRequested:106803] [debug] OpenShift client response: {"command":"oc annotate route jenkins --overwrite \"haproxy.router.openshift.io/timeout=120s\" --namespace \"bison-core-devops\" ","output":"route \"jenkins\" annotated\n","status":true}
2018-03-22T15:27:56.967Z [m:7:ebcb9ba5-91e7-4c6d-872d-d92c98eac5b1:Bison:DevOpsEnvironmentRequested:106804] [verbose] Executing oc command: oc get route/jenkins --output "jsonpath={.spec.host}" --namespace "bison-core-devops"
2018-03-22T15:27:57.224Z [m:7:ebcb9ba5-91e7-4c6d-872d-d92c98eac5b1:Bison:DevOpsEnvironmentRequested:107061] [debug] OpenShift client response: {"command":"oc get route/jenkins --output \"jsonpath={.spec.host}\" --namespace \"bison-core-devops\" ","output":"jenkins-bison-core-devops.apps.nonprod.ocp.absa.co.za","status":true}
2018-03-22T15:27:57.225Z [m:7:ebcb9ba5-91e7-4c6d-872d-d92c98eac5b1:Bison:DevOpsEnvironmentRequested:107062] [debug] Using Jenkins Route host [jenkins-bison-core-devops.apps.nonprod.ocp.absa.co.za] to add Bitbucket credentials
2018-03-22T15:27:57.228Z [m:7:ebcb9ba5-91e7-4c6d-872d-d92c98eac5b1:Bison:DevOpsEnvironmentRequested:107065] [debug] Stringifying URL encoded data: json=%7B%22%22%3A%220%22%2C%22credentials%22%3A%7B%22scope%22%3A%22GLOBAL%22%2C%22id%22%3A%22bison-core-devops-bitbucket%22%2C%22username%22%3A%22svc-subatomic%22%2C%22password%22%3A%22D7VFbB%28VCWrqNpFi%24BKPAdo%20%20%20%20%20%22%2C%22description%22%3A%22bison-core-devops-bitbucket%22%2C%22%24class%22%3A%22com.cloudbees.plugins.credentials.impl.UsernamePasswordCredentialsImpl%22%7D%7D
2018-03-22T15:27:57.247Z [m:7] [error] (node:7) Error: Network error: socket hang up
    at new ApolloError (/opt/app/node_modules/apollo-client/bundle.umd.js:76:28)
    at /opt/app/node_modules/apollo-client/bundle.umd.js:952:41
    at /opt/app/node_modules/apollo-client/bundle.umd.js:1338:17
    at Array.forEach (<anonymous>)
    at /opt/app/node_modules/apollo-client/bundle.umd.js:1337:18
    at Map.forEach (native)
    at QueryManager.broadcastQueries (/opt/app/node_modules/apollo-client/bundle.umd.js:1332:22)
    at /opt/app/node_modules/apollo-client/bundle.umd.js:901:31
    at propagateAslWrapper (/opt/app/node_modules/async-listener/index.js:502:23)
    at /opt/app/node_modules/async-listener/glue.js:188:31
    at /opt/app/node_modules/async-listener/index.js:539:70
    at /opt/app/node_modules/async-listener/glue.js:188:31
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
2018-03-22T15:27:57.248Z [m:7] [error] (node:7) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
    at emitWarning (internal/process/promises.js:78:15)
    at emitPendingUnhandledRejections (internal/process/promises.js:95:11)
    at process._tickCallback (internal/process/next_tick.js:189:7)
2018-03-22T15:27:57.496Z [m:7] [warn ] WebSocket connection closed with 1000:`

**Comment by donovanmuller** [comment]
This might be due to Node's single threaded nature. I.e. The `oc` process call is holding the thread and preventing the websocket from checking in and keeping the connection open.

Just a guess...

**Comment by chriskieser** [comment]
Was thinking the same thing...

**Comment by cdupuis** [comment]
When running the client in cluster mode that shouldn't happen.

**Comment by kbristow** [comment]
Does cluster mode require we are actually running on a cluster?

**Comment by cdupuis** [comment]
No, just enable cluster mode in your atomist.config.ts:

```
    cluster: {
        // This will run the client in cluster mode; master and workers
        enabled: process.env.NODE_ENV === "production",
    },
```

Make sure that NODE_ENV variable is properly set in your environments.

**Comment by kbristow** [comment]
Yeah saw that. Was just wondering if how/where it was deployed mattered when enabling this. Will give it a go. Thanks.

**Comment by cdupuis** [comment]
Deployment shouldn't matter. This is will launch a master node process that manages the WebSocket and HTTP traffic and dispatches to spawned worker processes. So the actual work happens in the worker, not blocking the main event loop of the master so that it stays responsive.

**Comment by kbristow** [comment]
Oh that is super cool. Nice!
