### ISSUE TITLE
Cannot use a private Slack channel as the Team channel

### ISSUE THREAD

**Issue by donovanmuller** [absa-subatomic/quantum-mechanic#40]
Atomist currently does not allow private Slack channels to be created.

This causes the following error when trying to link an existing Slack channel as the Team channel:

```console
xxx [m:35301:4513d3fc-45a8-4e3f-bd0d-0731353bec58:core-atomist:LinkExistingTeamSlackChannel:1265] [info ] Finished invocation of command 'LinkExistingTeamSlackChannel': {"code":1,"correlation_id":"330446c0-20a6-4062-a2c8-51eb321925d2","invocation_id":"4513d3fc-45a8-4e3f-bd0d-0731353bec58","message":"Network error: Response not successful: Received status code 400","stack":"Error: Network error: Response not successful: Received status code 400\n    at new ApolloError (.../subatomic/quantum-mechanic/node_modules/apollo-client/bundle.umd.js:76:28)\n    at Object.error (.../subatomic/quantum-mechanic/node_modules/apollo-client/bundle.umd.js:784:28)\n    at SubscriptionObserver.error (.../subatomic/quantum-mechanic/node_modules/apollo-link/node_modules/zen-observable/zen-observable.js:174:19)\n    at .../subatomic/quantum-mechanic/node_modules/apollo-link-http/lib/bundle.umd.js:151:26\n    at Promise.propagateAslWrapper (.../subatomic/quantum-mechanic/node_modules/async-listener/index.js:502:23)\n    at Promise.__asl_wrapper (.../subatomic/quantum-mechanic/node_modules/async-listener/glue.js:188:31)\n    at proxyWrapper (.../subatomic/quantum-mechanic/node_modules/async-listener/index.js:527:23)\n    at .../subatomic/quantum-mechanic/node_modules/async-listener/index.js:539:70\n    at .../subatomic/quantum-mechanic/node_modules/async-listener/glue.js:188:31\n    at <anonymous>"}
```

Until Atomist supports creating private Slack channels, we should handle this error gracefully and then link the existing private channel. The Atomist bot can still be invited and used in a private channel.

**Comment by donovanmuller** [comment]
Unfortunately there is no current way to link an existing Slack channel using the Atomist API's (other than creating a new one with `createChannel()` - which doesn't support private channels). This in turn means you cannot invite the Atomist bot to the existing private channel because a channel must exist in Cortex to do that.

One possible workaround is to use the Slack API ([groups.list](https://api.slack.com/methods/groups.list)) and get the channel Id and then explicitly add the `channel` to the know list of `ChatTeam` channels. However, the mutation to add an existing `ChatChannel` does not yet exist.

**Comment by donovanmuller** [comment]
On talking to the Atomist developers, a simpler solution is to make inviting the Atomist bot to the private channel _before_ linking, a prerequisite.
