### ISSUE TITLE
Investigate error after onboarding a team member

### ISSUE THREAD

**Issue by donovanmuller** [absa-subatomic/quantum-mechanic#68]
Seeing this error in the logs:

```console
xxx [m:92177:3f5af8f1-e44b-4545-b574-0f7418ccca68:core-atomist:TeamCreatedEvent:004] [error] Failed invocation of event subscription 'TeamCreatedEvent': {"name":"TypeError","message":"Cannot read property 'firstName' of null","stack":"TypeError: Cannot read property 'firstName' of null\n    at TeamCreated.handle (xxx/quantum-mechanic/build/src/gluon/team/TeamCreated.js:22:30)\n    at BuildableAutomationServer.invokeFreshEventHandlerInstance (xxx/quantum-mechanic/node_modules/@atomist/automation-client/server/BuildableAutomationServer.js:137:18)\n    at Object.invoke (xxx/quantum-mechanic/node_modules/@atomist/automation-client/server/BuildableAutomationServer.js:91:38)\n    at BuildableAutomationServer.invokeEventHandler (xxx/quantum-mechanic/node_modules/@atomist/automation-client/server/BuildableAutomationServer.js:107:24)\n    at Promise.all.h.map.eh (xxx/quantum-mechanic/node_modules/@atomist/automation-client/server/AbstractAutomationServer.js:18:49)\n    at Array.map (<anonymous>)\n    at BuildableAutomationServer.onEvent (xxx/quantum-mechanic/node_modules/@atomist/automation-client/server/AbstractAutomationServer.js:18:34)\n    at DefaultWebSocketRequestProcessor.invokeEvent (xxx/quantum-mechanic/node_modules/@atomist/automation-client/internal/transport/AbstractRequestProcessor.js:180:30)\n    at ses.run (xxx/quantum-mechanic/node_modules/@atomist/automation-client/internal/transport/AbstractRequestProcessor.js:84:18)\n    at Namespace.run (xxx/quantum-mechanic/node_modules/continuation-local-storage/context.js:48:5)\n    at DefaultWebSocketRequestProcessor.processEvent (xxx/quantum-mechanic/node_modules/@atomist/automation-client/internal/transport/AbstractRequestProcessor.js:58:13)\n    at invokeEventHandler (xxx/quantum-mechanic/node_modules/@atomist/automation-client/internal/transport/websocket/WebSocketClient.js:65:26)\n    at WebSocket.incoming (xxx/quantum-mechanic/node_modules/@atomist/automation-client/internal/transport/websocket/WebSocketClient.js:124:25)\n    at emitOne (events.js:116:13)\n    at WebSocket.emit (events.js:211:7)\n    at Receiver._receiver.onmessage (xxx/quantum-mechanic/node_modules/ws/lib/websocket.js:145:47)"}
```

Specifically: `Cannot read property 'firstName' of null`.

**Comment by kbristow** [comment]
This happens when you are not even creating a team. I have seen it too. Meant to bring it up.

**Comment by donovanmuller** [comment]
This issue originates in Gluon https://github.com/absa-subatomic/gluon/issues/35
